services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.14
    restart: unless-stopped
    network_mode: host
    stop_grace_period: 60s
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    env_file:
      - /srv/compose/omada/.env
    volumes:
      - /srv/appdata/omada/data:/opt/tplink/EAPController/data
      - /srv/appdata/omada/logs:/opt/tplink/EAPController/logs
