# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/533d337d-3c6e-474a-90f6-5b99f0b032cb";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "discard=async"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/533d337d-3c6e-474a-90f6-5b99f0b032cb";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "discard=async"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/533d337d-3c6e-474a-90f6-5b99f0b032cb";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" "discard=async"];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/533d337d-3c6e-474a-90f6-5b99f0b032cb";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" "discard=async"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9582-5301";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Storage mount for photos disk
  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/51BAE4A7240C12DE";
    fsType = "auto";
    options = [
      "nosuid"
      "nodev"
      "nofail"
      "x-gvfs-show"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
